GET http://localhost:5000/api/user/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDkzYmQwMzMxMGU4OTk4MjkxOWI2YmYiLCJlbWFpbCI6InZwb2x0YXZza2l5MHlAZ21haWwuY29tIiwiaWF0IjoxNjg4NjMwNDU5LCJleHAiOjE2ODg2MzQwNTl9.TW40TDpujAeUeB54CRDIKXP6yBqeVtBXlyR0niw4LQk HTTP/1.1
