GET http://localhost:5000/api/user/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDlmN2QyZTRhZTFiMTNhMjQyZTRiYzEiLCJlbWFpbCI6ImFhYUBhYWEuYWFhIiwiaWF0IjoxNjg4MTc0MDIwLCJleHAiOjE2ODgxNzc2MjB9.AF13oD_fCRMudgqXKRSltSuHU0bydnZ6AELc57-jBdc HTTP/1.1
