export default {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    SET_NUMBER: 'SET_NUMBER',
    REQUEST_COUNTER_FETCHING: 'REQUEST_COUNTER_FETCHING',
    REQUEST_COUNTER_SUCCESS: 'REQUEST_COUNTER_SUCCESS',
    REQUEST_COUNTER_ERROR: 'REQUEST_COUNTER_ERROR'
}